kind: pipeline
type: exec
name: default

trigger:
  event:
    - push

steps:
  - name: build
    commands:
      - docker build -t pywebio-chart .
  - name: deploy
    commands:
      - docker rm -f pywebio-charts || true
      - docker run --restart=always --name pywebio-charts -d pywebio-chart